# Application Name
spring.application.name=Women-Safety-Device

# Server Port
server.port=8082
server.address=0.0.0.0
# MongoDB Database Connection
mongodb+srv://hardiksoni5553_db_user:H@rdik1234@cluster1.taiknwi.mongodb.net/?appName=Cluster1
# Multipart file handling configuration (For Audio/Image Evidence Uploads)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary Configuration (Yahan apne actual credentials daalein)
cloudinary.cloud_name=agwxlsyz
cloudinary.api_key=795289554567365
cloudinary.api_secret=SBrFCTz6Tk-DxDgObohdAv3kMu4

